### ISSUE TITLE
Implement PSR-2 compability in code

### ISSUE THREAD

**Issue by seyfer** [alle/kohana-restful-api#1]
It's just about code style (braces, spaces, etc.)
Now code style not PSR and it's make code reading hard, because most developers use PSR style.

@alle, If it's okay, I can do this and will made pull request.

**Comment by alle** [comment]
@seyfer, I "inherited" the code, since it is a fork of [SupersonicAds/kohana-restful-api](https://github.com/alle/kohana-restful-api).
This code is mainly written following the [Kohana's Conventions and Coding Styles](http://kohanaframework.org/3.3/guide/kohana/conventions), which are followed by the Kohana Developers and Kohana Modules Developers.
I highly appreciate PSR initiatives and directives (I tend to follow them in my projects that does not involve Kohana). IMHO, any Kohana module should follow the [Kohana's Conventions and Coding Styles](http://kohanaframework.org/3.3/guide/kohana/conventions).
Your opinion is welcome.

**Comment by seyfer** [comment]
@alle , okay, you are right with coding style for Kohana.

But as my opinion there is no place for other standards, because PSR exists and if any framework will invent and follow own code style - PSR has no meaning in that case. 
PSR is for all php code, no matter which library or framework used.

Also developers IDE must be configured to PSR formatting by default (it's already in PhpStorm and NetBeans with small changes)

I think Kohana community should change their mind. 

So, this is just my opinion. If you reject this issue, i'am understand your decision.

**Comment by alle** [comment]
@seyfer, I agree with you: "Kohana community should change their mind".

Infact, if I code for Kohana, I have to switch my IDE formatting settings to the "Kohana" preset.
At the office, I inherited a coding style I should adhere to (no PSR, no Kohana, nothing); and I have to switch my IDE to that formatting preset. And so on.
Having the possibility to deal with an unique coding standard is like a _kimera_, if you want to respect other developers (even if other developers don't _respect_ you).

Anyway, the code in this repo is for Kohana Developers. So, if you don't mind, I would prefer to keep the code formatting as is, for now.

**Comment by seyfer** [comment]
@alle , Okay. Thank you for answer and explanation.

**Comment by alle** [comment]
Thank you to you, Sir.

-- 
Alessandro Frangioni
Il giorno 15 gennaio 2015 @ 10:57:14, Oleg Abrazhaev (notifications@github.com) ha scritto:

Closed #1.

**Comment by seyfer** [comment]
I'm started discussion here. Join if you wish.

https://github.com/kohana/core/issues/597

**Comment by alle** [comment]
Thanks for reporting it to me.
